<a href="https://colab.research.google.com/github/RogerHeederer/PyTorchNLPBook/blob/master/AboutTensor_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
torch.manual_seed(1234)

## Tensors
* 스칼라는 싱글 넘버이다
* 벡터는 숫자들의 어레이다
* 매트릭스는 숫자들로 이루어진 2D 어레이다.
* 텐서들은 숫자들로 이루어진 N-D 어레이다.

*텐서 생성하는 여러 방법*

In [2]:
# 텐서 생성
def describe(x): #텐서 부가 설명 함수
  print("Type: {}".format(x.type()))
  print("Shape/size: {}".format(x.shape))
  print("Values: \n{}".format(x))

In [3]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[3.1876e-36, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [4]:
describe(torch.randn(2,3)) #random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [5]:
describe(torch.rand(2,3)) #uniform random

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])


In [6]:
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
x = torch.Tensor(3,4).fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [10]:
#리스트로부터 가져와 생성하기
x = torch.Tensor(([1,2],
                  [2,4]))
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 2.],
        [2., 4.]])


In [11]:
#numpy matrics로부터 가져와 생성하기
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))
print(npy.dtype)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.6261, 0.9225, 0.3492],
        [0.5886, 0.2870, 0.7819]], dtype=torch.float64)
float64


###텐서 타입과 크기###

In [12]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [16]:
x = torch.randn(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.5385, -0.9757,  1.5769],
        [ 0.3840, -0.6039, -0.5240]])


###텐서 오퍼레이션###

In [17]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.0771, -1.9515,  3.1539],
        [ 0.7680, -1.2077, -1.0479]])


In [18]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.0771, -1.9515,  3.1539],
        [ 0.7680, -1.2077, -1.0479]])


In [19]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [20]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [21]:
describe(torch.sum(x, dim=0)) #가장 바깥 차원을 기준

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [22]:
describe(torch.sum(x, dim=1)) #그 다음 차원을 기준

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [23]:
describe(torch.transpose(x, 0, 1)) #0 행, 1 열

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


###텐서 indexing, slicing, joining###

In [24]:
x = torch.arange(6).view(2,3) # arange6 -> 0~5
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
x[0], x[1]

(tensor([0, 1, 2]), tensor([3, 4, 5]))

In [26]:
x[0,0:2], x[1,0:2]

(tensor([0, 1]), tensor([3, 4]))

In [27]:
x[0:1,0:2], x[1:2,0:2]

(tensor([[0, 1]]), tensor([[3, 4]]))

In [28]:
x[0:2,0:2]

tensor([[0, 1],
        [3, 4]])

In [29]:
x[:1, :2]

tensor([[0, 1]])

In [30]:
x[0, 1]

tensor(1)

In [31]:
x = torch.randn(3, 4)
x

tensor([[-0.4175,  0.7618,  0.5356,  1.5739],
        [-0.4864, -0.6622, -0.4790,  0.8539],
        [-0.2285,  0.3081,  1.1171,  0.1585]])

dim=0, dim=1 을 이해함에 있어서 행,열 기준으로 봐야하는지 차원으로 봐야하는 지 계속 헷갈리는데,
[[]] 이렇게 2차원이 있을 때 dim = 0은 가장 바깥쪽 []이라 생각하고 dim=1은  [ '[]' ] 여기에 '[]' 안에 있는 요소라 생각해보자

그럼 dim=0으로 indices를 쓰면, 가장 바깥쪽 [ ] 안에는 [ ], [ ], [ ]  이렇게 3덩이가 들어있다

여기서 0번째, 2번째꺼 빼오면 아래와 같은 결과가 나오며

dim=1로 indices를 쓰면, 가장 안쪽 요소  [ ], [ ], [ ] 여기에서 0번째 2번째꺼 빼오는 식으로 생각하면 아래 결과

In [32]:
indices = torch.tensor([0,2])
torch.index_select(x, 0, indices) # x를 가져와 dim=0을 기준으로 index는 indces를 사용한다.

tensor([[-0.4175,  0.7618,  0.5356,  1.5739],
        [-0.2285,  0.3081,  1.1171,  0.1585]])

In [33]:
torch.index_select(x, 1, indices)# x를 가져와 dim=1을 기준으로 index는 indces를 사용한다.

tensor([[-0.4175,  0.5356],
        [-0.4864, -0.4790],
        [-0.2285,  1.1171]])

In [38]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
row_indices, col_indices

(tensor([0, 1]), tensor([0, 1]))

In [39]:
describe(x[row_indices, col_indices])

Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([-0.4175, -0.6622])


In [40]:
x = torch.LongTensor(([1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]))

describe(x)
print(x.dtype)
print(x.numpy().dtype)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
int64


In [41]:
x = torch.FloatTensor(([1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]))

describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [42]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [43]:
x = torch.arange(0, 10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [45]:
x = torch.arange(0, 10).long()
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Tensor Operation

In [46]:
x = torch.arange(0, 20)

In [47]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [48]:
print(x.view(1,20)) # dimension이 하나 추가된다

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])


In [49]:
print(x.view(2,10))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


In [51]:
x = torch.arange(12).view(3,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [53]:
y = torch.arange(4).view(1,4)
print(y)

tensor([[0, 1, 2, 3]])


In [54]:
print(x+y) #broadcasting

tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])


In [55]:
z = torch.arange(3).view(3,1)
print(z)

tensor([[0],
        [1],
        [2]])


In [56]:
print(x+z) #broadcasting

tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])


In [57]:
print(y+z) #broadcasting

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])


In [59]:
x = torch.arange(12).view(3, 4)
print(x.shape)
x

torch.Size([3, 4])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [64]:
x = x.unsqueeze(dim=1)
print(x.shape)
x

torch.Size([3, 1, 4])


tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [65]:
x = x.squeeze()
print(x.shape)
x

torch.Size([3, 4])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [67]:
x = torch.rand(3,4)
print("x: \n", x)
print("--")
print("torch.add(x, x): \n", torch.add(x, x))
print("--")
print("x+x: \n", x + x)

x: 
 tensor([[0.8043, 0.3186, 0.2908, 0.4196],
        [0.3728, 0.3769, 0.0108, 0.9455],
        [0.7661, 0.2634, 0.1880, 0.5174]])
--
torch.add(x, x): 
 tensor([[1.6086, 0.6372, 0.5816, 0.8392],
        [0.7456, 0.7538, 0.0216, 1.8910],
        [1.5322, 0.5268, 0.3761, 1.0348]])
--
x+x: 
 tensor([[1.6086, 0.6372, 0.5816, 0.8392],
        [0.7456, 0.7538, 0.0216, 1.8910],
        [1.5322, 0.5268, 0.3761, 1.0348]])


In [69]:
x = torch.arange(12).reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [70]:
print(x.add_(x))

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])


In [71]:
x = torch.arange(12).reshape(3, 4)
print("x: \n", x)

x: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [72]:
print("Summing across rows(dim=0): \n", x.sum(dim=0))

Summing across rows(dim=0): 
 tensor([12, 15, 18, 21])


In [74]:
print("Summing across cols(dim=1): \n", x.sum(dim=1))

Summing across cols(dim=1): 
 tensor([ 6, 22, 38])


## Indexing, Slicing, Joining, Mutating

Indexing

In [75]:
x = torch.arange(6).view(2, 3)
print("x: \n", x)

x: 
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [76]:
print("x[:2, :2] -> \n", x[:2, :2])

x[:2, :2] -> 
 tensor([[0, 1],
        [3, 4]])


In [77]:
print("x[0][1]: \n", x[0][1])

x[0][1]: 
 tensor(1)


In [78]:
print("Setting [0][1] to be 8")
x[0][1] = 8
print(x)

Setting [0][1] to be 8
tensor([[0, 8, 2],
        [3, 4, 5]])


Index_select

In [79]:
x = torch.arange(9).view(3,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [80]:
indices = torch.LongTensor([0, 2])
torch.index_select(x, dim=0, index=indices)

tensor([[0, 1, 2],
        [6, 7, 8]])

In [81]:
indices = torch.LongTensor([0, 2])
torch.index_select(x, dim=1, index=indices)

tensor([[0, 2],
        [3, 5],
        [6, 8]])

numpy-style advanced indexing

In [85]:
x = torch.arange(9).view(3,3)
indices = torch.LongTensor([0, 2])
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [86]:
x[indices]

tensor([[0, 1, 2],
        [6, 7, 8]])

In [87]:
x[indices, :]

tensor([[0, 1, 2],
        [6, 7, 8]])

In [88]:
x[:, indices]

tensor([[0, 2],
        [3, 5],
        [6, 8]])

In [89]:
x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [90]:
describe(torch.cat([x, x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [91]:
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [92]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [93]:
x = torch.arange(9).view(3,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [94]:
new_x = torch.cat([x,x,x], dim=1)

In [95]:
print(new_x.shape)
print(new_x)

torch.Size([3, 9])
tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8, 6, 7, 8]])


In [97]:
x = torch.arange(9).view(3,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [98]:
new_x = torch.stack([x, x, x])
print(new_x.shape)
print(new_x)

torch.Size([3, 3, 3])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


Linear Algebra Tensor Function

In [108]:
x = torch.arange(0, 12).view(3,4)
print("x: \n", x)
print("---")
# 이 조건에서는 (0번째)x=3  (1번째)y=4라고 하자

x: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
---


In [110]:
print(x.transpose(1,0)) # y를 앞에, x를 뒤에
x.transpose(1,0).shape

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


torch.Size([4, 3])

In [111]:
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])

In [113]:
x = x.view(batch_size, seq_size, feature_size)
print(x.shape) # 0번째 x:3 / 1번째 y:4 / 2번째 z:5

torch.Size([3, 4, 5])


In [114]:
print(x)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


In [123]:
print(x.transpose(1,0).shape) #x와 y의 위치 변경
print(x.transpose(2,1).shape) #y와 z의 위치 변경
print(x.transpose(2,0).shape) #x와 z의 위치 변경

torch.Size([4, 3, 5])
torch.Size([3, 5, 4])
torch.Size([5, 4, 3])


In [124]:
print(x.transpose(1,0))

tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


In [125]:
print(x.transpose(2,1))

tensor([[[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]],

        [[20, 25, 30, 35],
         [21, 26, 31, 36],
         [22, 27, 32, 37],
         [23, 28, 33, 38],
         [24, 29, 34, 39]],

        [[40, 45, 50, 55],
         [41, 46, 51, 56],
         [42, 47, 52, 57],
         [43, 48, 53, 58],
         [44, 49, 54, 59]]])


In [126]:
print(x.transpose(2,0))

tensor([[[ 0, 20, 40],
         [ 5, 25, 45],
         [10, 30, 50],
         [15, 35, 55]],

        [[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]],

        [[ 2, 22, 42],
         [ 7, 27, 47],
         [12, 32, 52],
         [17, 37, 57]],

        [[ 3, 23, 43],
         [ 8, 28, 48],
         [13, 33, 53],
         [18, 38, 58]],

        [[ 4, 24, 44],
         [ 9, 29, 49],
         [14, 34, 54],
         [19, 39, 59]]])


Permute

In [131]:
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("x.shape: \n", x.shape)
print(x)

x.shape: 
 torch.Size([3, 4, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


In [133]:
# 3->0, 4->1, 5->2
print("x.permute(1, 0, 2).shape: \n", x.permute(1, 0, 2).shape)
print(x.permute(1,0,2)) #(4,3,5)

x.permute(1, 0, 2).shape: 
 torch.Size([4, 3, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


In [134]:
print(x.permute(2,1,0)) #(5,4,3)

tensor([[[ 0, 20, 40],
         [ 5, 25, 45],
         [10, 30, 50],
         [15, 35, 55]],

        [[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]],

        [[ 2, 22, 42],
         [ 7, 27, 47],
         [12, 32, 52],
         [17, 37, 57]],

        [[ 3, 23, 43],
         [ 8, 28, 48],
         [13, 33, 53],
         [18, 38, 58]],

        [[ 4, 24, 44],
         [ 9, 29, 49],
         [14, 34, 54],
         [19, 39, 59]]])


Matrix multipication

In [135]:
torch.randn(2, 3, requires_grad=True)

tensor([[-0.2107,  1.1399, -2.5122],
        [ 1.3823,  0.9847,  1.4719]], requires_grad=True)

In [136]:
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [137]:
x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [138]:
describe(torch.mm(x1, x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [139]:
x = torch.arange(0, 12).view(3,4).float()
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [140]:
x2 = torch.ones(4, 2)
x2[:, 1] += 1
print(x2)

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])


In [141]:
print(x.mm(x2))

tensor([[ 6., 12.],
        [22., 44.],
        [38., 76.]])
